const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const key='vesta-v5';const state=JSON.parse(localStorage.getItem(key)||'null')||{done:{},custom:[],mood:'',cart:0,streak:9,period:false};
const tasks=[['cleanse','شست‌وشوی صورت','ژل ملایم','۰۷:۳۰'],['vitc','سرم ویتامین C','۲ تا ۳ قطره','۰۷:۴۰'],['spf','ضدآفتاب','SPF 50','۰۷:۴۵'],['walk','۲۰ دقیقه حرکت','پیاده‌روی یا کشش','۱۷:۰۰'],['night','روتین شب','پاکسازی + مرطوب‌کننده','۲۲:۳۰']];
const save=()=>localStorage.setItem(key,JSON.stringify(state));
function rows(){return [...tasks.map(t=>({id:t[0],title:t[1],detail:t[2],time:t[3]})),...state.custom]}
function renderTasks(){const wrap=$('#todayTaskList');if(!wrap)return;wrap.innerHTML=rows().map(t=>`<article class="task ${state.done[t.id]?'done':''}" data-id="${t.id}"><button class="task-check">${state.done[t.id]?'✓':''}</button><div><strong>${t.title}</strong><small>${t.detail}</small></div><em>${t.time}</em></article>`).join('');$$('.task-check',wrap).forEach(b=>b.onclick=()=>{const id=b.closest('.task').dataset.id;state.done[id]=!state.done[id];save();renderTasks();toast(state.done[id]?'ثبت شد':'برگشت')});update()}
function update(){const r=rows(),d=r.filter(t=>state.done[t.id]).length,p=Math.round(d/r.length*100);$('#doneCount').textContent=fa(d);$('#totalCount').textContent=fa(r.length);$('#heroPercent').textContent=fa(p)+'٪';$('#weekPercent').textContent=fa(Math.max(58,Math.round((p+75)/2)))+'٪';$('#streakValue').textContent=fa(state.streak);$('#cartCount').textContent=fa(state.cart)}
function switchView(v){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.view===v));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===v));history.replaceState(null,'','#'+v);scrollTo({top:0,behavior:'smooth'})}
$$('[data-nav]').forEach(b=>b.onclick=()=>switchView(b.dataset.nav));
$('#startToday')?.addEventListener('click',()=>$('#todayTaskList')?.scrollIntoView({behavior:'smooth'}));
const q=$('#quickAddDialog');$('#quickAddBtn')?.addEventListener('click',()=>q.showModal());$('#quickAddForm')?.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const i=$('#customTaskInput'),v=i.value.trim();if(!v){e.preventDefault();return}e.preventDefault();state.custom.push({id:'c'+Date.now(),title:v,detail:'کار شخصی',time:'امروز'});i.value='';q.close();save();renderTasks();toast('به امروز اضافه شد')});
const md=$('#moodDialog');$('#logMoodBtn')?.addEventListener('click',()=>md.showModal());$$('[data-mood]').forEach(b=>b.onclick=()=>{state.mood=b.dataset.mood;save();md.close();toast('حال امروز ثبت شد')});
$('#logPeriodBtn')?.addEventListener('click',()=>{state.period=!state.period;save();toast(state.period?'پریود ثبت شد':'ثبت حذف شد')});
$$('.add-cart').forEach(b=>b.onclick=()=>{state.cart++;save();update();toast('به سبد اضافه شد')});$('#notifyBtn')?.addEventListener('click',()=>toast('اعلان جدیدی نداری'));
function calendar(){const g=$('#calendarGrid');if(!g)return;let h='';for(let i=0;i<35;i++){const d=((i+27)%31)+1;let c='';if([5,6,7,8,9].includes(d))c='period';if([23,24,25,26,27].includes(d))c+=(c?' ':'')+'predict';if(d===18)c+=(c?' ':'')+'today';h+=`<span class="${c}">${fa(d)}</span>`}g.innerHTML=h}
function heat(){const h=$('#heatmap');if(!h)return;const a=[1,2,2,0,3,4,2,1,0,2,3,3,1,0,4,2,3,2,1,0,2,4,4,3,2,1,0,2];h.innerHTML=a.map(v=>`<i class="l${v}"></i>`).join('')}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),1600)}
try{$('#todayDate').textContent=new Intl.DateTimeFormat('fa-IR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}catch{}
calendar();heat();renderTasks();const hash=location.hash.slice(1);if(['today','plan','cycle','discover','me'].includes(hash))switchView(hash);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});