const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const faDigits=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const state=JSON.parse(localStorage.getItem('vesta-state')||'null')||{period:'morning',done:{},custom:[],mood:'',lazy:false,streak:9,cart:2};
const baseTasks={morning:[['💧','یک لیوان آب','شروع آروم روز'],['◌','شستن صورت','ژل شست‌وشوی ملایم'],['✦','سرم ویتامین C','۲ تا ۳ قطره'],['☀','ضدآفتاب','SPF 50 — دو بند انگشت']],day:[['🚶🏻‍♀️','۲۰ دقیقه حرکت','پیاده‌روی یا کشش'],['💧','آب تا ظهر','هدف: ۴ لیوان'],['🙂','Mood check','حالت رو ثبت کن']],night:[['☾','پاکسازی شب','آرایش و آلودگی روز'],['✦','مرطوب‌کننده','لایه نازک و یکنواخت'],['〰','روتین مو','سرم ساقه مو'],['😴','آماده خواب','۳۰ دقیقه بدون صفحه‌نمایش']]};
function save(){localStorage.setItem('vesta-state',JSON.stringify(state))}
function taskKey(period,index,label){return `${period}:${index}:${label}`}
function currentTasks(){return [...baseTasks[state.period],...state.custom.filter(x=>x.period===state.period).map(x=>['＋',x.label,'کار شخصی'])]}
function renderTasks(){const list=$('#routineList');const tasks=currentTasks();list.innerHTML=tasks.map((t,i)=>{const key=taskKey(state.period,i,t[1]);const done=!!state.done[key];return `<article class="task ${done?'done':''}" data-key="${encodeURIComponent(key)}"><span class="task-icon">${t[0]}</span><div class="task-copy"><strong>${t[1]}</strong><small>${t[2]}</small></div><button class="check" aria-label="انجام شد">${done?'✓':''}</button></article>`}).join('');$$('.task .check',list).forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.task');const key=decodeURIComponent(card.dataset.key);state.done[key]=!state.done[key];save();renderTasks();updateScore();if(state.done[key])toast('عالیه ✦ یک قدم برای خودت')}));updateProgressCopy()}
function allTaskKeys(){return Object.entries(baseTasks).flatMap(([p,arr])=>arr.map((t,i)=>taskKey(p,i,t[1]))).concat(state.custom.map((x,i)=>taskKey(x.period,baseTasks[x.period].length+i,x.label)))}
function updateScore(){const keys=allTaskKeys();const count=keys.filter(k=>state.done[k]).length;const score=keys.length?Math.round(count/keys.length*100):0;$('#glowScore').textContent=faDigits(score);$('#glowRing').style.setProperty('--p',score);$('#weeklyScore').textContent=faDigits(Math.max(65,Math.round((score+78)/2)));updateProgressCopy()}
function updateProgressCopy(){const tasks=currentTasks();const keys=tasks.map((t,i)=>taskKey(state.period,i,t[1]));const c=keys.filter(k=>state.done[k]).length;$('#progressCopy').textContent=`${faDigits(c)} از ${faDigits(keys.length)}`}
function switchView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('[data-nav]').forEach(b=>{if(b.closest('.bottom-nav'))b.classList.toggle('active',b.dataset.nav===view)});window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${view}`)}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.nav)));
$$('.day-pill').forEach(b=>b.addEventListener('click',()=>{state.period=b.dataset.period;$$('.day-pill').forEach(x=>x.classList.toggle('active',x===b));save();renderTasks()}));
function buildCalendar(){const grid=$('#calendarGrid');let html='';for(let i=1;i<=35;i++){const day=((i+26)%31)+1;let cls='';if([5,6,7,8,9].includes(day))cls='period';if([14,15,16,17].includes(day))cls='fertile';if(day===20)cls+=' today';html+=`<span class="${cls}">${faDigits(day)}</span>`}grid.innerHTML=html}
$$('[data-mood]').forEach(b=>b.addEventListener('click',()=>{state.mood=b.dataset.mood;$$('[data-mood]').forEach(x=>x.classList.toggle('selected',x===b));save();toast(`حال امروز: ${b.dataset.mood}`)}));
const dialog=$('#quickAddDialog');$('#quickAddBtn').addEventListener('click',()=>dialog.showModal());$('#quickAddForm').addEventListener('submit',e=>{const input=$('#customTaskInput');if(e.submitter?.value==='cancel')return;const label=input.value.trim();if(!label)return;e.preventDefault();state.custom.push({period:state.period,label});save();input.value='';dialog.close();renderTasks();updateScore();toast('به روتینت اضافه شد ✦')});
$('#lazyModeBtn').addEventListener('click',()=>{state.lazy=!state.lazy;save();$('#lazyModeBtn').textContent=state.lazy?'حالت عادی':'حالت سبک';toast(state.lazy?'امروز فقط ضروری‌ها؛ بدون عذاب وجدان ♡':'برگشتی به روتین کامل')});
$('#shareBtn').addEventListener('click',async()=>{const text='این هفته ۸۲٪ به روتینم پایبند بودم ✦ Vesta';try{if(navigator.share)await navigator.share({title:'Vesta Weekly Glow',text});else{await navigator.clipboard.writeText(text);toast('متن گزارش کپی شد')}}catch{}});
$$('.add-cart').forEach(b=>b.addEventListener('click',()=>{state.cart++;save();const badge=$('.bag i');if(badge)badge.textContent=faDigits(state.cart);toast('به سبد خرید اضافه شد ♡')}));
$$('.challenge-list article>button').forEach(btn=>btn.addEventListener('click',()=>{btn.textContent='شروع شد ✓';btn.disabled=true;toast('چالش به برنامه‌ات اضافه شد')}));
$('#notifyBtn').addEventListener('click',()=>toast('فعلاً اعلان جدیدی نداری ♡'));$('#profileBtn').addEventListener('click',()=>toast('پروفایل و شخصی‌سازی در نسخه بعدی'));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
function initDate(){try{const d=new Intl.DateTimeFormat('fa-IR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#todayDate').textContent=d}catch{}}
function init(){initDate();buildCalendar();$$('.day-pill').forEach(b=>b.classList.toggle('active',b.dataset.period===state.period));if(state.mood){const m=$(`[data-mood="${state.mood}"]`);if(m)m.classList.add('selected')}$('#lazyModeBtn').textContent=state.lazy?'حالت عادی':'حالت سبک';$('#streakValue').textContent=faDigits(state.streak);const badge=$('.bag i');if(badge)badge.textContent=faDigits(state.cart);renderTasks();updateScore();const hash=location.hash.replace('#','');if(['today','routine','cycle','progress','challenges','shop'].includes(hash))switchView(hash);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
init();