const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const storageKey='vesta-v3';
const state=JSON.parse(localStorage.getItem(storageKey)||'null')||{done:{},custom:[],mood:'',lazy:false,cart:0,streak:9,periodLogged:false};
const tasks=[{id:'cleanse',title:'شست‌وشوی صورت',detail:'روتین صبح',time:'صبح'},{id:'vitc',title:'سرم ویتامین C',detail:'۲ تا ۳ قطره',time:'صبح'},{id:'spf',title:'ضدآفتاب',detail:'SPF 50',time:'صبح'},{id:'walk',title:'۲۰ دقیقه حرکت',detail:'پیاده‌روی یا کشش',time:'عصر'},{id:'night',title:'پاکسازی و مرطوب‌کننده',detail:'نسخه سبک امشب',time:'شب'}];
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
function getTasks(){const base=state.lazy?tasks.filter(t=>['cleanse','spf','night'].includes(t.id)):tasks;return [...base,...state.custom]}
function renderTasks(){const list=$('#todayTaskList');if(!list)return;const rows=getTasks();list.innerHTML=rows.map(t=>`<article class="today-task ${state.done[t.id]?'done':''}" data-id="${t.id}"><button class="task-check" aria-label="انجام شد"></button><div class="task-copy"><strong>${t.title}</strong><small>${t.detail}</small></div><span class="task-time">${t.time}</span></article>`).join('');$$('.task-check',list).forEach(b=>b.onclick=()=>{const id=b.closest('.today-task').dataset.id;state.done[id]=!state.done[id];save();renderTasks();if(state.done[id])toast('ثبت شد')});updateProgress()}
function updateProgress(){const rows=getTasks(),done=rows.filter(t=>state.done[t.id]).length,total=rows.length,pct=total?Math.round(done/total*100):0;$('#heroProgress').textContent=fa(pct);$('#heroProgressRing').style.setProperty('--progress',pct);$('#heroTaskCount').textContent=fa(total);$('#weekPercent').textContent=fa(Math.max(55,Math.round((pct+72)/2)))+'٪';$('#streakValue').textContent=fa(state.streak)}
function switchView(view){$$('.screen').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));history.replaceState(null,'',`#${view}`);window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.nav)));
$$('[data-plan-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-plan-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-plan-panel]').forEach(p=>p.classList.toggle('active',p.dataset.planPanel===b.dataset.planTab))}));
$$('[data-discover-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-discover-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-discover-panel]').forEach(p=>p.classList.toggle('active',p.dataset.discoverPanel===b.dataset.discoverTab))}));
$$('[data-discover-tab-jump]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const val=b.dataset.discoverTabJump;const tab=$(`[data-discover-tab="${val}"]`);if(tab)tab.click()}));
const quick=$('#quickAddDialog');$('#quickAddBtn')?.addEventListener('click',()=>quick.showModal());$('#quickAddForm')?.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const input=$('#customTaskInput'),title=input.value.trim();if(!title){e.preventDefault();return}e.preventDefault();state.custom.push({id:`custom-${Date.now()}`,title,detail:'کار شخصی',time:'امروز'});save();input.value='';quick.close();renderTasks();toast('به امروز اضافه شد')});
$('#lazyModeBtn')?.addEventListener('click',()=>{state.lazy=!state.lazy;save();renderTasks();$('#lazyModeBtn em').textContent=state.lazy?'برگشت به کامل':'سبک‌ترش کن';toast(state.lazy?'امروز فقط ضروری‌ها':'روتین کامل برگشت')});
const moodDialog=$('#moodDialog');$('#moodQuickBtn')?.addEventListener('click',()=>moodDialog.showModal());$('#logMoodBtn')?.addEventListener('click',()=>moodDialog.showModal());$$('[data-mood]').forEach(b=>b.addEventListener('click',()=>{state.mood=b.dataset.mood;save();$('#moodQuickText').textContent=state.mood;setTimeout(()=>moodDialog.close(),80);toast('حال امروز ثبت شد')}));
$('#logPeriodBtn')?.addEventListener('click',()=>{state.periodLogged=!state.periodLogged;save();$('#logPeriodBtn').classList.toggle('active',state.periodLogged);toast(state.periodLogged?'روز پریود ثبت شد':'ثبت پریود حذف شد')});
$('#logSymptomBtn')?.addEventListener('click',()=>toast('ثبت علائم در نسخه بعدی باز می‌شه'));
$$('.add-cart').forEach(b=>b.addEventListener('click',()=>{state.cart++;save();$('#cartCount').textContent=fa(state.cart);toast('به سبد اضافه شد')}));
$('#notifyBtn')?.addEventListener('click',()=>toast('اعلان جدیدی نداری'));
function buildCalendar(){const grid=$('#calendarGrid');if(!grid)return;const days=[];for(let i=0;i<35;i++)days.push(((i+28)%31)+1);grid.innerHTML=days.map(day=>{let cls='';if([5,6,7,8,9].includes(day))cls='period';if([23,24,25,26,27].includes(day))cls='prediction';if(day===20)cls+=(cls?' ':'')+'today';return `<span class="${cls}">${fa(day)}</span>`}).join('')}
function buildHeatmap(){const h=$('#heatmap');if(!h)return;const values=[1,2,2,0,3,4,2,1,0,2,3,3,1,0,4,2,3,2,1,0,2,4,4,3,2,1,0,2,3,4,2,2,3,1,0,4,3,2,2,1,3,4,2,1,0,2,3,4,4,2];h.innerHTML=values.map(v=>`<i class="l${v}"></i>`).join('')}
function initDate(){try{$('#todayDate').textContent=new Intl.DateTimeFormat('fa-IR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}catch{}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__vestaToast);window.__vestaToast=setTimeout(()=>t.classList.remove('show'),1700)}
function init(){initDate();buildCalendar();buildHeatmap();renderTasks();$('#cartCount').textContent=fa(state.cart);if(state.mood)$('#moodQuickText').textContent=state.mood;$('#logPeriodBtn')?.classList.toggle('active',state.periodLogged);const hash=location.hash.replace('#','');if(['today','plan','cycle','discover','me'].includes(hash))switchView(hash);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
init();
